name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-11
          - gcc-10
          - gcc-9
          - clang-14
          - clang-13
          - clang-12
          - clang-11
          - clang-10
          - clang-9
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_conan:
    runs-on: ubuntu-latest
    name: "Conan ${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          export CONAN_GCC_VERSIONS=11
          export CONAN_DOCKER_IMAGE=conanio/gcc${CONAN_GCC_VERSIONS}
          script/conan_build.sh
